# Use an official Node.js image that matches your host's version
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the application code into the container
COPY app.js .

# Command to run when the container starts
CMD [ "node", "app.js" ]
